export const allowedUsers = [
  "speed admin",
  "adam martins dos santos",
  "adriano jose fernandes de faria",
  "aislan reis bastos",
  "alan antonio de amorim neto",
  "alan rodrigues silva",
  "alex da costa freitas maldonado",
  "alex oliveira macedo",
  "ana clara duarte dantas",
  "ana paula piunti novaes",
  "andre luiz faria de castro",
  "anna julia de faria",
  "antonio edson teixeira junior",
  "arthur fernando salles bernardo",
  "bruno jacomini",
  "brusle goncalves remidio",
  "catia milene crepaldi",
  "danrlei levandowski xavier",
  "dassaieve albuquerque taveira",
  "edilson martins do nascimento",
  "eduardo yuji kinjo da silva",
  "ezedo lucas da rocha moreira",
  "francisco de paula lima",
  "francisco josiel dos santos matos",
  "francisco lucas silva marques",
  "gabriel santos correa de moraes",
  "gabriel severo brittes",
  "gilmar francisco zwetsch",
  "gregory santos de oliveira",
  "guilherme augusto casonato",
  "guilherme dos santos wadenphul",
  "gustavo garcia cardoso",
  "gustavo pereira",
  "guterman oliveira dos santos",
  "henrique de souza barcelos",
  "hureverson marcelino domingues da silva",
  "jesse osvaldo antonio gomes fernandes",
  "joaffison dos santos silva",
  "joao eduardo ribeiro ramos",
  "jose antonio vaccaro junior",
  "jose ilton vieira de sousa",
  "josimar alberto silva gomes",
  "julio cesar frontine de brito",
  "julio cesar renouleau serrano",
  "kalahan de campos",
  "larissa gabriele de lima silveira",
  "leandro rocha nacano",
  "leonardo batista braga",
  "leonardo dias ribeiro",
  "leonardo henrique oliveira de souza",
  "louryval soares melo raposo",
  "lucas soares ribeiro",
  "luis henrique moronary de souza",
  "marco jose marques",
  "marcorelio nascimento dornelas",
  "marcos antonio da silva brito",
  "maria eduarda moura rezende",
  "mariana carolina tabile",
  "marina euzebio baptista santos",
  "matheus moreira santos",
  "matheus salomao cardoso ferreira",
  "mauricio mendes santos",
  "mayke tibes de paula lourenco",
  "miller tadeu do nascimento",
  "milton de souza frazao neto",
  "mingpei wu",
  "nielton zanetti dos santos",
  "paulo ricardo fidencio",
  "pedro henrique nunes da silva laurentino",
  "rafael antonio da costa cacemiro",
  "reginaldo de lima",
  "renan lucas pinto bertolino",
  "renata brito de sousa",
  "robson joacir ferrazza basso",
  "robson luis figueiredo",
  "rodrigo arruda gomes de sousa",
  "rodrigo mazzoni bergami",
  "saulo rodrigues xavier",
  "sergio ieler",
  "stepherson santos correa",
  "tatiana de souza franca",
  "thiago ramos correia",
  "thiago rosa cardoso",
  "tiago bispo de freitas",
  "tone ramos evangelista de souza",
  "waldir pereira alves junior",
  "wanderson mendes da silva",
  "wellington castro de assis",
  "willian cleber camilo",
];
